### ISSUE TITLE
Implement testing of settings

### ISSUE THREAD

**Issue by rutsky** [butorov/sentry-telegram#8]
It would be nice if plugin had some "test settings" action that would try to send test notification (to check, that bot token and receiver ids are correct).

**Comment by butorov** [comment]
Hello.
This problem was fixed in new Sentry's versions. Try to update your instance to 8.19.0 or above.
I got it on 8.19.0.
In Telegram:
![image](https://user-images.githubusercontent.com/5171644/32135451-b51c592e-bc29-11e7-950c-fc88c1f1381b.png)
In Sentry:
![image](https://user-images.githubusercontent.com/5171644/32135461-d2401fd6-bc29-11e7-8139-f0d82689b502.png)
